### PR TITLE
Update Amplitude version to 2.2.1

### PR DESCRIPTION
**Pull request by curtisliu**

### CODE REVIEW

**Comment by f2prateek** [comment]
Can you provide a description of the setting so we can add it to our web UI?

**Comment by curtisliu** [comment]
Setting trackReferrer to true will send referrer information as a user property to Amplitude:
(see https://github.com/amplitude/Amplitude-javascript#configuration-options)

**Comment by curtisliu** [comment]
hey, just wanted to check the status on this. thanks!

**Comment by curtisliu** [comment]
@f2prateek anything you need from me to help this along?

**Comment by f2prateek** [comment]
LGTM! just forgot about it sorry.

**Comment by curtisliu** [comment]
thanks!

**Pull request merged**
