### PR TITLE
Updating amplitude SDK v2.6.0

### PR DESCRIPTION
**Pull request by djih**
Migrating cookie data to local storage: https://github.com/amplitude/Amplitude-Javascript/releases/tag/v2.6.0

### CODE REVIEW

**Comment by djih** [comment]
@f2prateek : thanks! Any idea when Segment will release the next version with this update?

**Comment by wcjohnson11** [comment]
@djih , I'll try to release this afternoon and will reply back here when it's deployed.

**Comment by wcjohnson11** [comment]
@djih this has been deployed and is now live. Thanks for the PR!

**Comment by djih** [comment]
@wcjohnson11 : sweet thanks!

**Pull request merged**
